# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
- group: mj-general

name: $(Build.DefinitionName)_$(GitVersion.InformationalVersion)
pool:
  vmImage: 'VS2017-Win2016' #  options: 'Ubuntu 16.04', 'macOS 10.13', 'VS2017-Win2016'

steps:
- task: gittools.gitversion.gitversion-task.GitVersion@4
  displayName: GitVersion
  
- powershell: Install-Module ModuleBuilder -Force
  displayName: Install ModuleBuilder module
  
- powershell: Import-Module ModuleBuilder -force; Build-Module ./Source/ -SemVer $(GitVersion.InformationalVersion) -Verbose
  displayName: 'Build module using ModuleBuilder'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Module'
  inputs:
    ArtifactName: Module
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    
- powershell: Publish-Module -Path ./output/AzureDevopsHelpers/ -NugetApiKey $(PowerShellGalleryApiKey)
